/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ResumeRouteImport } from "./routes/resume";
import { Route as ApplicationsRouteImport } from "./routes/applications";
import { Route as IndexRouteImport } from "./routes/index";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ResumeRoute = ResumeRouteImport.update({
  id: "/resume",
  path: "/resume",
  getParentRoute: () => rootRouteImport,
} as any);
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: "/applications",
  path: "/applications",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/applications": typeof ApplicationsRoute;
  "/resume": typeof ResumeRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/applications": typeof ApplicationsRoute;
  "/resume": typeof ResumeRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/applications": typeof ApplicationsRoute;
  "/resume": typeof ResumeRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/applications" | "/resume" | "/settings";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/applications" | "/resume" | "/settings";
  id: "__root__" | "/" | "/applications" | "/resume" | "/settings";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApplicationsRoute: typeof ApplicationsRoute;
  ResumeRoute: typeof ResumeRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/resume": {
      id: "/resume";
      path: "/resume";
      fullPath: "/resume";
      preLoaderRoute: typeof ResumeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/applications": {
      id: "/applications";
      path: "/applications";
      fullPath: "/applications";
      preLoaderRoute: typeof ApplicationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
